### ISSUE TITLE
cellranger reboot

### ISSUE THREAD

**Issue by jennybc** [chainsawriot/readODS#25]
Hi @chainsawriot,

[`cellranger`](https://github.com/jennybc/cellranger) is getting a major reboot, because I need it to do more than it currently does. And I have to update it, to get compatible with the new `testthat`.

Do I have this right? The only place you use it is here:

https://github.com/chainsawriot/readODS/blob/ee96772d4de374b17d533fa5861feeb55130d1ef/R/readODS.R#L200

and the only function you use is `cellranger::as.cell_limits()`? You use it just to parse a single range that might look like `A5:D12`?

I'm not sure if the `cell_limits` object will survive, but obviously something equivalent would take its place. It just might be a little bit different. I will let you know...

**Comment by chainsawriot** [comment]
@jennybc Thanks for making [`cellranger`](https://github.com/jennybc/cellranger) better! And yes, I have `only as.cell_limit()` in readODS.

I hope that there will be backward compatible equivalent of `cell_limit` object because not everyone is using the latest version of cellranger. If the reboot is too radical, please let me know the change. I think I can adapt to it with thing like

```{r}
select_range <- function(raw_sheet, range) {
    if (packageVersion('cellranger') <= "1.0.0.9000") {
        range_select <- cellranger::as.cell_limits(range)
        selected_sheet <- raw_sheet[range_select$ul[1]:range_select$lr[1], range_select$ul[2]:range_select$lr[2]]
    } else {
        ## let me know how the new version works. Thanks
    }
    
    return(selected_sheet)
}
```

**Comment by jennybc** [comment]
Since you are the only person using it in a package besides me, I might take advantage of that and let myself rename things. I'll be back in touch.
